### ISSUE TITLE
Can't integrate MSF and BeEF

### ISSUE THREAD

**Issue by Gee94** [beefproject/beef#1543]
Couldn't find another thread that resolved my issue 

#### Environment

What version/revision of BeEF are you using?
4.7.0

On what version of Ruby?
ruby 2.5.1p57
On what browser?
n/a
On what operating system?
Kali 2018

#### Configuration

Are you using a non-default configuration?
no 
Have you enabled or disabled any BeEF extensions?
Disabled Demo enabled MSF extension

#### Summary
BeEf works but cant integrate the MSF modules into BeEF

#### Expected Behaviour

Metasploit modules to be loaded

#### Actual Behaviour

None loaded

#### Steps to Reproduce

Started MSGRPC manually to coincide with the settings in the metasploit extension config.yaml 

Run ./beef

[16:50:29][*] Connecting to Metasploit on 127.0.0.1:55552
[16:50:29][!] Metasploit: undefined method `to_msgpack' for ["auth.login", "msf", "msf"]:Array
[16:50:29][!] API Fire Error: authentication failed in {:owner=>BeEF::Extension::Metasploit::API::MetasploitHooks, :id=>17}.post_soft_load()
[16:50:29][*] BeEF is loading. Wait a few seconds...

[16:50:29][!] API Fire Error: undefined method `remap' for nil:NilClass in {:owner=>BeEF::Extension::AdminUI::API::Handler, :id=>21}.mount_handler()

**Comment by bcoles** [comment]
That's a new one. BeEF hasn't been tested much on Ruby 2.5.x. I'm not sure that the msfrpc Ruby Gem has been tested on 2.5.x either.

**Comment by Gee94** [comment]
Downgraded ruby to 2.4.1 and it works again

**Comment by github1973** [comment]
i have the same problem,everything is ok,but when i ./beef -x then display "API Fire Error: execution expired in {:owner=>BeEF::Extension"
i don't know what;s the fuck...
Maybe the probelm with Ruby version

Waiting.......

**Comment by bcoles** [comment]
@github1973 make sure your BeEF is up to date. Don't use Ruby 2.5.x.

**Comment by github1973** [comment]
@bcoles this is new bug ?

Thanks very much!  I will use rvm to install Ruby2.4.1 and try again! Do u have telegram? I have a lot of questions to ask U about Beef+Metasploit .....

**Comment by github1973** [comment]
@bcoles you are so good man for new guys~

**Comment by bcoles** [comment]
@github1973 I do what I can.

I don't have telegram.

I'm not sure if this is a new bug. In my minimal testing, BeEF works with Ruby 2.5.1 on Kali 2018. However, there are issues with database locking, so Ruby 2.5 is not recommended.

There might be issues with the `msfrpc` Ruby gem and Ruby 2.5.1. I haven't tested the Metasploit integration with Ruby 2.5.x.

To be honest, Metasploit integration isn't very useful unless you're going to script up some automatic browser fingerprinting and exploitation. You can achieve the exact same thing by running a Metasploit browser exploit in `msfconsole`, then using BeEf's `Create Invisible Iframe` command module to point the browser to the exploit.

**Comment by github1973** [comment]
@bcoles oK,.the problem with my Linux kali 4.9.0-kali3-amd64 #1 SMP Debian 4.9.18-1kali1 (2017-04-04) x86_64 GNU/Linux

i am downloading the new version https://images.offensive-security.com/virtual-images/kali-linux-2018.1-vm-amd64.torrent then may cross the problem, i have remembered that don't use ruby2.5. This is not bug,just a little problem.

I agree u, Metasploit integration isn't very useful.......

Thanks a lot,

The tools so great !

**Comment by bcoles** [comment]
@github1973 Kali 2018.1 uses Ruby 2.3.1; however if you do `apt-get update` then it will upgrade to Ruby 2.5.1.

You don't need to upgrade Kali to fix your problem. You need to update BeEF.

**Comment by github1973** [comment]
@bcoles,i understand what i need to do..thanks

**Comment by github1973** [comment]
@bcoles,i have add your twitter.but i can't send message, how can i connect u? in the irc channel?

**Comment by H4xl0r** [comment]
the trick is to downgrade the Ruby version via rvm ... 
to 2.4.1 or the 2.3.1
on Kali u need to install rvm first .... (Kali 2018)
then u can set it as default make bundle install and run beef 
i think this could be closed .

IF U USE KALI 2018:
there is a working version of Beef integrated , under /usr/share/beef-xss/beef
so u just have to go to there and fire it up with ./beef 
it will work without any downgrading 
the settings file for this beef is under /etc/beef-xss/config ....

**Comment by H4xl0r** [comment]
Downgrading via rvm to ruby 2.3.0 not connecting API error (used both downgraded msfconsole & beef)
                      via rvm to ruby 2.4.1 not connecting API error (used both downgraded msfconsole & beef)

**Comment by H4xl0r** [comment]
install rvm https://rvm.io/rvm/install , downgrade to 2.4.1 can confirm all works then.
Can be closed

**Comment by bcoles** [comment]
This should be fixed for Ruby 2.5.x in f0310b34d94a49e1ab16e19d419bee0c61895a1c.

There's still a couple of issues.

* Auto loading msfrpcd is broken due to Ruby environment. Not many people use this functionality anyway, opting instead to first start Metasploit, then connect to it with BeEF. This is the preferred approach too.
* Attempting to retrieve the results of a Metasploit exploit command module results in a stack trace. Given that the modules result in a shell (or don't), and generally don't return much in the way of output beyond `iframe created`, this isn't a big deal.

Closing this issue.
